### ISSUE TITLE
reproduce

### ISSUE THREAD

**Issue by zzl2022** [rajpurkarlab/2021-fall-chest-ct#1]
hi,
This is an excellent repository. I have successfully preprocessed the data according to the guidelines. But when I tried to train a model, the error was as follows:
"
omegaconf.errors.ConfigAttributeError: Missing key min_abnormal_slice
    full_key: data.min_abnormal_slice
    object_type=dict
"
How can I solve this bug? 
Look forward to your reply!
Thanks.

**Comment by alexxke** [comment]
Thanks! You can set `data.min_abnormal_slice` in the experiment config yaml.
